apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadebackend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: arcadebackend      
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: arcadebackend        
    spec:
      containers:
      - name: arcadebackend
        image: dzbuild.azurecr.io//azure-adventure-day-coach/gamebot:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: calc-frontend         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
