apiVersion: v1
kind: Service
metadata:
    name: "dzvnets-41e4"
    labels:
        app: "dzvnets-41e4"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "dzvnets-41e4"