apiVersion: v1
kind: Service
metadata:
  name: arcadebackend
  labels:
    name: arcadebackend    
spec:
  selector:
    name: arcadebackend    
  type: LoadBalancer
  ports:
   - port: 80
     name: arcadebackend
     targetPort: 8080
     protocol: TCP
