apiVersion: v1
kind: Service
metadata:
    name: "linkerd2-b480"
    labels:
        app: "linkerd2-b480"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "linkerd2-b480"