on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dzbuild.azurecr.io
        username: ${{ secrets.acr_dzbuild_username }}
        password: ${{ secrets.acr_dzbuild_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/GameBot" -f  "GameBot/Dockerfile" -t dzbuild.azurecr.io/linkerd2:${{ github.sha }}
        docker push dzbuild.azurecr.io/linkerd2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_linkerd2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: dzbuild.azurecr.io
        container-registry-username: ${{ secrets.acr_dzbuild_username }}
        container-registry-password: ${{ secrets.acr_dzbuild_password }}
        secret-name: linkerd2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          dzbuild.azurecr.io/linkerd2:${{ github.sha }}
        imagepullsecrets: |
          linkerd2dockerauth